apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spring-boot
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - image: 339095555060.dkr.ecr.ap-south-1.amazonaws.com/manoj99:latest
          imagePullPolicy: Always
          name: spring-boot
          ports:
            - containerPort: 8080
