apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: spring-boot
    app.kubernetes.io/managed-by: kubectl
  name: spring-boot
spec:
  selector:
    app: spring-boot
  type: NodePort
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 8080